[package]
name = "leptrino-ros2"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
leptrino-force-torque-sensor = "0.1.0"
r2r = "0.9.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[profile.release]
opt-level = 3
debug = false
lto = true